// src/app/privacy/page.tsx
'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui';
import { useTranslation } from 'react-i18next';

export default function PrivacyPolicyPage() {
  const { t } = useTranslation();

  return (
    <div className="container mx-auto max-w-4xl py-12 px-4">
      <Card>
        <CardHeader>
          <CardTitle className="text-3xl">{t('Privacy Policy')}</CardTitle>
        </CardHeader>
        <CardContent className="prose dark:prose-invert max-w-none">
          <p>
            <strong>{t('Last updated')}: 23 July 2025</strong>
          </p>
          <p>
            {t(
              'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.'
            )}
          </p>

          <h2 className="text-2xl font-semibold mt-6">{t('1. Data Controller')}</h2>
          <p>
            {t(
              'The data controller for PingPongTracker (hereinafter "the Service") is Arttu Sulkonen.'
            )}
          </p>
          <p>
            {t('If you have any questions about this Privacy Policy, you can contact us:')}
          </p>
          <ul>
            <li>{t('By email:')} arttu.sulkonen@icloud.com</li>
          </ul>

          <h2 className="text-2xl font-semibold mt-6">{t('2. Data We Collect')}</h2>
          <p>{t('We collect the following types of information:')}</p>
          <ul>
            <li>
              <strong>{t('Personal Data:')}</strong>{' '}
              {t(
                'While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This includes: Email address, Display Name, Profile Picture (optional), and a short biography (optional).'
              )}
            </li>
            <li>
              <strong>{t('Usage Data:')}</strong>{' '}
              {t(
                'This includes data generated by your activity on the Service, such as match history, scores, ELO ratings, room memberships, and tournament participation.'
              )}
            </li>
          </ul>

          <h2 className="text-2xl font-semibold mt-6">{t('3. Purpose of Data Processing')}</h2>
          <p>{t('We use your data for the following purposes:')}</p>
          <ul>
            <li>
              <strong>{t('To provide and maintain our Service:')}</strong>{' '}
              {t(
                'including to monitor the usage of our Service, calculate ratings, and manage rooms and tournaments.'
              )}
            </li>
            <li>
              <strong>{t('To manage Your Account:')}</strong>{' '}
              {t(
                'to manage your registration as a user of the Service. The Personal Data you provide can give you access to different functionalities of the Service.'
              )}
            </li>
            <li>
              <strong>{t('For social features:')}</strong>{' '}
              {t(
                'Your display name and optional profile picture are visible to other users to facilitate interaction within rooms and tournaments.'
              )}
            </li>
          </ul>

          <h2 className="text-2xl font-semibold mt-6">{t('4. Data Storage and Security')}</h2>
          <p>
            {t(
              'Your data is stored and processed using Google Cloud Platform services, specifically Firebase (Firestore, Firebase Storage, Firebase Authentication).'
            )}
          </p>
          <ul>
            <li>
              <strong>{t('Data Location:')}</strong>{' '}
              {t(
                'Our primary data processing and storage facilities for Firestore and Cloud Functions are located in the europe-west1 (Belgium) region. Firebase Storage may store data in a multi-region configuration which could include servers outside of the EU, primarily in the United States. Google maintains a high standard of security and data protection across all its services.'
              )}
            </li>
            <li>
              <strong>{t('Security:')}</strong>{' '}
              {t(
                'We implement security measures to protect your data. However, no method of transmission over the Internet or method of electronic storage is 100% secure.'
              )}
            </li>
          </ul>

          <h2 className="text-2xl font-semibold mt-6">{t('5. Your GDPR Rights')}</h2>
          <p>
            {t(
              'You have the right to access, rectify, or erase your personal data, as well as other rights as established by the GDPR:'
            )}
          </p>
          <ul>
            <li>
              <strong>{t('Access:')}</strong>{' '}
              {t('You can view your data on your profile page.')}
            </li>
            <li>
              <strong>{t('Rectification:')}</strong>{' '}
              {t('You can edit your profile information in your account settings.')}
            </li>
            <li>
              <strong>{t('Erasure ("Right to be forgotten"):')}</strong>{' '}
              {t(
                'You can delete your account from your profile settings. Upon deletion, your personal data (email, name, photo) will be anonymized or removed. Your match history will be retained in an anonymized form to maintain the integrity of other users\' statistics.'
              )}
            </li>
          </ul>

          <h2 className="text-2xl font-semibold mt-6">{t('6. Data Retention')}</h2>
          <p>
            {t(
              'We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.'
            )}
          </p>

          <h2 className="text-2xl font-semibold mt-6">{t('7. Changes to this Privacy Policy')}</h2>
          <p>
            {t(
              'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.'
            )}
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
